version: "3"
services:
  springBootApp:
    image: zamo12345/user-service:1.1
    container_name: docker-postgres-springboot-demo-app
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-demo-db
    ports:
      - "8081:8082"
    networks:
      - network
    depends_on:
      - postgresDB
    restart: on-failure
  postgresDB:
    image: postgres:13.2
    container_name: docker-postgres-springboot-demo-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=310155
      - POSTGRES_DB=scientest
networks:
  network:
volumes:
  volume: